### ISSUE TITLE
Mentor: Definitions Tab > Can I set the label of the unknown entity in the tab?

### ISSUE THREAD

**Issue by k00ni** [faubulous/mentor-vscode#43]
In the "Mentor: Definitions" tab there is an entity which is labelled **unknown**. What is that and can I label it with my own RDF?

![Bildschirmfoto vom 2024-11-26 13-05-38](https://github.com/user-attachments/assets/5fe6ac5c-1710-4c87-9c06-f056ce1df43b)

**Comment by faubulous** [comment]
`unknown` refers to the source of definition which is usually the OWL ontology header or a SKOS concept scheme. If none of both is available, the entities that share a common namespace are grouped together in an 'unkown' group.

Try to add a `rdf:type owl:Ontology` to your definition at line 7 and the source should show the value of `skos:prefLabel`. The order in which multiple label predicates are prioritized can be changed in the Mentor settings `Mentor > Predicates: Label`:

![image](https://github.com/user-attachments/assets/0286ece4-1dce-4c74-b4a3-e7badbda8b00)

If you edit the `settings.json` file you should see something like this. The order of the predicates in the list indicates which predicate is prefferred for displaying labels. The ones that match first will be picked over all the others:

```
"mentor.predicates.label": [
        "http://purl.org/dc/terms/title",
        "http://purl.org/dc/elements/1.1/title",
        "http://www.w3.org/2004/02/skos/core#prefLabel",
        "http://www.w3.org/2000/01/rdf-schema#label",
        "https://schema.org/name",
        "http://schema.org/name",
        "http://www.w3.org/ns/shacl#path"
    ]
```

**Comment by k00ni** [comment]
Thanks!
